export const employees = [
  {
    "id": 1,
    "firstName": "John",
    "lastName": "Smith",
    "email": "john.smith@company.com",
    "department": "Engineering",
    "position": "Senior Developer",
    "salary": 95000,
    "hireDate": "2021-03-15",
    "age": 32,
    "location": "New York",
    "performanceRating": 4.2,
    "projectsCompleted": 12,
    "isActive": true,
    "skills": ["JavaScript", "React", "Node.js"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 2,
    "firstName": "Emily",
    "lastName": "Davis",
    "email": "emily.davis@company.com",
    "department": "Marketing",
    "position": "Marketing Manager",
    "salary": 78000,
    "hireDate": "2020-07-22",
    "age": 29,
    "location": "Los Angeles",
    "performanceRating": 4.5,
    "projectsCompleted": 8,
    "isActive": true,
    "skills": ["Digital Marketing", "SEO", "Analytics"],
    "manager": "Michael Brown"
  },
  {
    "id": 3,
    "firstName": "Michael",
    "lastName": "Brown",
    "email": "michael.brown@company.com",
    "department": "Marketing",
    "position": "VP Marketing",
    "salary": 125000,
    "hireDate": "2019-01-10",
    "age": 38,
    "location": "Los Angeles",
    "performanceRating": 4.7,
    "projectsCompleted": 15,
    "isActive": true,
    "skills": ["Strategy", "Leadership", "Brand Management"],
    "manager": null
  },
  {
    "id": 4,
    "firstName": "Sarah",
    "lastName": "Johnson",
    "email": "sarah.johnson@company.com",
    "department": "Engineering",
    "position": "Engineering Manager",
    "salary": 115000,
    "hireDate": "2018-11-05",
    "age": 35,
    "location": "New York",
    "performanceRating": 4.6,
    "projectsCompleted": 18,
    "isActive": true,
    "skills": ["Team Leadership", "Architecture", "Python"],
    "manager": "David Wilson"
  },
  {
    "id": 5,
    "firstName": "David",
    "lastName": "Wilson",
    "email": "david.wilson@company.com",
    "department": "Engineering",
    "position": "CTO",
    "salary": 180000,
    "hireDate": "2017-05-12",
    "age": 42,
    "location": "New York",
    "performanceRating": 4.8,
    "projectsCompleted": 25,
    "isActive": true,
    "skills": ["Technical Strategy", "Leadership", "Cloud Architecture"],
    "manager": null
  },
  {
    "id": 6,
    "firstName": "Lisa",
    "lastName": "Garcia",
    "email": "lisa.garcia@company.com",
    "department": "Sales",
    "position": "Sales Representative",
    "salary": 65000,
    "hireDate": "2022-02-28",
    "age": 26,
    "location": "Chicago",
    "performanceRating": 3.9,
    "projectsCompleted": 6,
    "isActive": true,
    "skills": ["CRM", "Negotiation", "Customer Relations"],
    "manager": "Robert Martinez"
  },
  {
    "id": 7,
    "firstName": "Robert",
    "lastName": "Martinez",
    "email": "robert.martinez@company.com",
    "department": "Sales",
    "position": "Sales Manager",
    "salary": 92000,
    "hireDate": "2020-09-14",
    "age": 34,
    "location": "Chicago",
    "performanceRating": 4.3,
    "projectsCompleted": 11,
    "isActive": true,
    "skills": ["Sales Strategy", "Team Management", "B2B Sales"],
    "manager": "Jennifer Lee"
  },
  {
    "id": 8,
    "firstName": "Jennifer",
    "lastName": "Lee",
    "email": "jennifer.lee@company.com",
    "department": "Sales",
    "position": "VP Sales",
    "salary": 135000,
    "hireDate": "2019-06-18",
    "age": 40,
    "location": "Chicago",
    "performanceRating": 4.6,
    "projectsCompleted": 16,
    "isActive": true,
    "skills": ["Strategic Sales", "Leadership", "Market Analysis"],
    "manager": null
  },
  {
    "id": 9,
    "firstName": "James",
    "lastName": "Anderson",
    "email": "james.anderson@company.com",
    "department": "HR",
    "position": "HR Specialist",
    "salary": 58000,
    "hireDate": "2021-08-30",
    "age": 28,
    "location": "Austin",
    "performanceRating": 4.0,
    "projectsCompleted": 7,
    "isActive": true,
    "skills": ["Recruitment", "Employee Relations", "HRIS"],
    "manager": "Karen White"
  },
  {
    "id": 10,
    "firstName": "Karen",
    "lastName": "White",
    "email": "karen.white@company.com",
    "department": "HR",
    "position": "HR Manager",
    "salary": 85000,
    "hireDate": "2019-12-02",
    "age": 36,
    "location": "Austin",
    "performanceRating": 4.4,
    "projectsCompleted": 13,
    "isActive": true,
    "skills": ["HR Strategy", "Policy Development", "Leadership"],
    "manager": null
  },
  {
    "id": 11,
    "firstName": "Alex",
    "lastName": "Thompson",
    "email": "alex.thompson@company.com",
    "department": "Engineering",
    "position": "Junior Developer",
    "salary": 72000,
    "hireDate": "2023-01-16",
    "age": 24,
    "location": "New York",
    "performanceRating": 3.8,
    "projectsCompleted": 4,
    "isActive": true,
    "skills": ["Java", "Spring Boot", "MySQL"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 12,
    "firstName": "Maria",
    "lastName": "Rodriguez",
    "email": "maria.rodriguez@company.com",
    "department": "Finance",
    "position": "Financial Analyst",
    "salary": 68000,
    "hireDate": "2021-11-08",
    "age": 30,
    "location": "Miami",
    "performanceRating": 4.1,
    "projectsCompleted": 9,
    "isActive": true,
    "skills": ["Financial Modeling", "Excel", "SAP"],
    "manager": "Thomas Clark"
  },
  {
    "id": 13,
    "firstName": "Thomas",
    "lastName": "Clark",
    "email": "thomas.clark@company.com",
    "department": "Finance",
    "position": "Finance Manager",
    "salary": 98000,
    "hireDate": "2018-04-25",
    "age": 37,
    "location": "Miami",
    "performanceRating": 4.5,
    "projectsCompleted": 14,
    "isActive": true,
    "skills": ["Financial Planning", "Budget Management", "Leadership"],
    "manager": null
  },
  {
    "id": 14,
    "firstName": "Amanda",
    "lastName": "Taylor",
    "email": "amanda.taylor@company.com",
    "department": "Marketing",
    "position": "Content Specialist",
    "salary": 55000,
    "hireDate": "2022-06-12",
    "age": 25,
    "location": "Los Angeles",
    "performanceRating": 3.7,
    "projectsCompleted": 5,
    "isActive": true,
    "skills": ["Content Writing", "Social Media", "Adobe Creative"],
    "manager": "Michael Brown"
  },
  {
    "id": 15,
    "firstName": "Ryan",
    "lastName": "Miller",
    "email": "ryan.miller@company.com",
    "department": "Engineering",
    "position": "DevOps Engineer",
    "salary": 88000,
    "hireDate": "2020-10-19",
    "age": 31,
    "location": "Seattle",
    "performanceRating": 4.3,
    "projectsCompleted": 10,
    "isActive": true,
    "skills": ["AWS", "Docker", "Kubernetes"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 16,
    "firstName": "Jessica",
    "lastName": "Moore",
    "email": "jessica.moore@company.com",
    "department": "Sales",
    "position": "Account Executive",
    "salary": 75000,
    "hireDate": "2021-04-03",
    "age": 27,
    "location": "Denver",
    "performanceRating": 4.0,
    "projectsCompleted": 8,
    "isActive": false,
    "skills": ["Account Management", "Salesforce", "Presentation"],
    "manager": "Robert Martinez"
  },
  {
    "id": 17,
    "firstName": "Daniel",
    "lastName": "Harris",
    "email": "daniel.harris@company.com",
    "department": "Finance",
    "position": "Senior Accountant",
    "salary": 73000,
    "hireDate": "2019-08-14",
    "age": 33,
    "location": "Miami",
    "performanceRating": 4.2,
    "projectsCompleted": 12,
    "isActive": true,
    "skills": ["Accounting", "Tax Preparation", "QuickBooks"],
    "manager": "Thomas Clark"
  },
  {
    "id": 18,
    "firstName": "Nicole",
    "lastName": "Jackson",
    "email": "nicole.jackson@company.com",
    "department": "HR",
    "position": "Recruiter",
    "salary": 62000,
    "hireDate": "2022-09-05",
    "age": 29,
    "location": "Austin",
    "performanceRating": 3.9,
    "projectsCompleted": 6,
    "isActive": true,
    "skills": ["Talent Acquisition", "LinkedIn Recruiter", "Interviewing"],
    "manager": "Karen White"
  },
  {
    "id": 19,
    "firstName": "Kevin",
    "lastName": "Wright",
    "email": "kevin.wright@company.com",
    "department": "Engineering",
    "position": "QA Engineer",
    "salary": 76000,
    "hireDate": "2020-12-07",
    "age": 30,
    "location": "Seattle",
    "performanceRating": 4.1,
    "projectsCompleted": 11,
    "isActive": true,
    "skills": ["Test Automation", "Selenium", "API Testing"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 20,
    "firstName": "Stephanie",
    "lastName": "Lopez",
    "email": "stephanie.lopez@company.com",
    "department": "Marketing",
    "position": "Digital Marketing Specialist",
    "salary": 64000,
    "hireDate": "2021-12-20",
    "age": 26,
    "location": "Phoenix",
    "performanceRating": 3.8,
    "projectsCompleted": 7,
    "isActive": true,
    "skills": ["Google Ads", "Facebook Ads", "Email Marketing"],
    "manager": "Michael Brown"
  },
  {
    "id": 21,
    "firstName": "Olivia",
    "lastName": "Green",
    "email": "olivia.green@company.com",
    "department": "Engineering",
    "position": "Frontend Developer",
    "salary": 72000,
    "hireDate": "2022-07-11",
    "age": 27,
    "location": "Boston",
    "performanceRating": 4.1,
    "projectsCompleted": 6,
    "isActive": true,
    "skills": ["React", "TypeScript", "CSS"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 22,
    "firstName": "Ethan",
    "lastName": "Walker",
    "email": "ethan.walker@company.com",
    "department": "Sales",
    "position": "Business Development",
    "salary": 67000,
    "hireDate": "2021-05-14",
    "age": 30,
    "location": "Chicago",
    "performanceRating": 3.9,
    "projectsCompleted": 5,
    "isActive": true,
    "skills": ["Negotiation", "CRM", "Cold Calling"],
    "manager": "Robert Martinez"
  },
  {
    "id": 23,
    "firstName": "Sophia",
    "lastName": "Turner",
    "email": "sophia.turner@company.com",
    "department": "HR",
    "position": "HR Coordinator",
    "salary": 60000,
    "hireDate": "2020-09-03",
    "age": 28,
    "location": "Austin",
    "performanceRating": 4.2,
    "projectsCompleted": 9,
    "isActive": true,
    "skills": ["Onboarding", "Recruitment", "Payroll"],
    "manager": "Karen White"
  },
  {
    "id": 24,
    "firstName": "Daniel",
    "lastName": "Evans",
    "email": "daniel.evans@company.com",
    "department": "Finance",
    "position": "Financial Controller",
    "salary": 102000,
    "hireDate": "2019-06-21",
    "age": 39,
    "location": "Miami",
    "performanceRating": 4.6,
    "projectsCompleted": 15,
    "isActive": true,
    "skills": ["Budgeting", "Forecasting", "Excel"],
    "manager": "Thomas Clark"
  },
  {
    "id": 25,
    "firstName": "Ava",
    "lastName": "Hernandez",
    "email": "ava.hernandez@company.com",
    "department": "Engineering",
    "position": "Backend Developer",
    "salary": 86000,
    "hireDate": "2022-03-10",
    "age": 29,
    "location": "San Francisco",
    "performanceRating": 4.3,
    "projectsCompleted": 8,
    "isActive": true,
    "skills": ["Node.js", "Express", "MongoDB"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 26,
    "firstName": "Matthew",
    "lastName": "Baker",
    "email": "matthew.baker@company.com",
    "department": "Engineering",
    "position": "Full Stack Developer",
    "salary": 94000,
    "hireDate": "2020-12-14",
    "age": 33,
    "location": "Seattle",
    "performanceRating": 4.5,
    "projectsCompleted": 14,
    "isActive": true,
    "skills": ["React", "Node.js", "GraphQL"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 27,
    "firstName": "Chloe",
    "lastName": "Adams",
    "email": "chloe.adams@company.com",
    "department": "Marketing",
    "position": "SEO Specialist",
    "salary": 59000,
    "hireDate": "2021-01-28",
    "age": 26,
    "location": "Los Angeles",
    "performanceRating": 3.8,
    "projectsCompleted": 7,
    "isActive": true,
    "skills": ["SEO", "Google Analytics", "Content Strategy"],
    "manager": "Michael Brown"
  },
  {
    "id": 28,
    "firstName": "William",
    "lastName": "Hall",
    "email": "william.hall@company.com",
    "department": "Finance",
    "position": "Auditor",
    "salary": 75000,
    "hireDate": "2019-11-19",
    "age": 36,
    "location": "Dallas",
    "performanceRating": 4.1,
    "projectsCompleted": 10,
    "isActive": true,
    "skills": ["Auditing", "Compliance", "Accounting"],
    "manager": "Thomas Clark"
  },
  {
    "id": 29,
    "firstName": "Ella",
    "lastName": "Scott",
    "email": "ella.scott@company.com",
    "department": "Sales",
    "position": "Sales Associate",
    "salary": 58000,
    "hireDate": "2022-10-04",
    "age": 25,
    "location": "Denver",
    "performanceRating": 3.7,
    "projectsCompleted": 4,
    "isActive": true,
    "skills": ["CRM", "Presentation", "Negotiation"],
    "manager": "Robert Martinez"
  },
  {
    "id": 30,
    "firstName": "James",
    "lastName": "Moore",
    "email": "james.moore@company.com",
    "department": "Engineering",
    "position": "DevOps Engineer",
    "salary": 91000,
    "hireDate": "2020-08-24",
    "age": 35,
    "location": "New York",
    "performanceRating": 4.4,
    "projectsCompleted": 12,
    "isActive": true,
    "skills": ["AWS", "Docker", "CI/CD"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 31,
    "firstName": "Liam",
    "lastName": "Hughes",
    "email": "liam.hughes@company.com",
    "department": "Marketing",
    "position": "Content Writer",
    "salary": 54000,
    "hireDate": "2022-01-12",
    "age": 27,
    "location": "San Diego",
    "performanceRating": 3.9,
    "projectsCompleted": 6,
    "isActive": true,
    "skills": ["Content Creation", "Copywriting", "Social Media"],
    "manager": "Michael Brown"
  },
  {
    "id": 32,
    "firstName": "Isabella",
    "lastName": "Clark",
    "email": "isabella.clark@company.com",
    "department": "HR",
    "position": "HR Generalist",
    "salary": 66000,
    "hireDate": "2021-03-08",
    "age": 31,
    "location": "Austin",
    "performanceRating": 4.0,
    "projectsCompleted": 8,
    "isActive": true,
    "skills": ["Employee Relations", "Policy Development", "Onboarding"],
    "manager": "Karen White"
  },
  {
    "id": 33,
    "firstName": "Benjamin",
    "lastName": "Perez",
    "email": "benjamin.perez@company.com",
    "department": "Engineering",
    "position": "Software Architect",
    "salary": 130000,
    "hireDate": "2018-05-17",
    "age": 41,
    "location": "San Francisco",
    "performanceRating": 4.7,
    "projectsCompleted": 20,
    "isActive": true,
    "skills": ["System Design", "Architecture", "Cloud"],
    "manager": "David Wilson"
  },
  {
    "id": 34,
    "firstName": "Mia",
    "lastName": "Ramirez",
    "email": "mia.ramirez@company.com",
    "department": "Sales",
    "position": "Account Manager",
    "salary": 82000,
    "hireDate": "2020-06-29",
    "age": 33,
    "location": "Chicago",
    "performanceRating": 4.2,
    "projectsCompleted": 9,
    "isActive": true,
    "skills": ["Client Management", "Negotiation", "CRM"],
    "manager": "Jennifer Lee"
  },
  {
    "id": 35,
    "firstName": "Lucas",
    "lastName": "Torres",
    "email": "lucas.torres@company.com",
    "department": "Engineering",
    "position": "QA Engineer",
    "salary": 78000,
    "hireDate": "2021-09-20",
    "age": 29,
    "location": "Seattle",
    "performanceRating": 4.1,
    "projectsCompleted": 11,
    "isActive": true,
    "skills": ["Automation", "Cypress", "Manual Testing"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 36,
    "firstName": "Harper",
    "lastName": "Nguyen",
    "email": "harper.nguyen@company.com",
    "department": "Finance",
    "position": "Treasury Analyst",
    "salary": 72000,
    "hireDate": "2022-05-09",
    "age": 28,
    "location": "Miami",
    "performanceRating": 4.0,
    "projectsCompleted": 7,
    "isActive": true,
    "skills": ["Financial Analysis", "Liquidity Management", "Excel"],
    "manager": "Thomas Clark"
  },
  {
    "id": 37,
    "firstName": "Henry",
    "lastName": "Lopez",
    "email": "henry.lopez@company.com",
    "department": "Engineering",
    "position": "Mobile Developer",
    "salary": 89000,
    "hireDate": "2021-11-15",
    "age": 30,
    "location": "San Jose",
    "performanceRating": 4.3,
    "projectsCompleted": 10,
    "isActive": true,
    "skills": ["Flutter", "React Native", "Kotlin"],
    "manager": "Sarah Johnson"
  },
  {
    "id": 38,
    "firstName": "Amelia",
    "lastName": "King",
    "email": "amelia.king@company.com",
    "department": "HR",
    "position": "Recruitment Specialist",
    "salary": 61000,
    "hireDate": "2020-04-23",
    "age": 29,
    "location": "Austin",
    "performanceRating": 3.8,
    "projectsCompleted": 6,
    "isActive": true,
    "skills": ["Recruitment", "Interviewing", "ATS"],
    "manager": "Karen White"
  },
  {
    "id": 39,
    "firstName": "Alexander",
    "lastName": "Carter",
    "email": "alexander.carter@company.com",
    "department": "Engineering",
    "position": "Data Scientist",
    "salary": 115000,
    "hireDate": "2019-07-15",
    "age": 34,
    "location": "New York",
    "performanceRating": 4.6,
    "projectsCompleted": 13,
    "isActive": true,
    "skills": ["Python", "Machine Learning", "SQL"],
    "manager": "David Wilson"
  },
  {
    "id": 40,
    "firstName": "Charlotte",
    "lastName": "Bell",
    "email": "charlotte.bell@company.com",
    "department": "Marketing",
    "position": "Brand Manager",
    "salary": 88000,
    "hireDate": "2021-02-01",
    "age": 32,
    "location": "Los Angeles",
    "performanceRating": 4.3,
    "projectsCompleted": 9,
    "isActive": true,
    "skills": ["Branding", "Market Analysis", "Strategy"],
    "manager": "Michael Brown"
  }
];